server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: user-service

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/fintrack_user
    username: root
    password: 7008
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Flyway Configuration for DB migrations
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Eureka Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

# Actuator for health checks and metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always