package com.personalfinance.expense.entity;

public enum ExpenseCategory {
    GROCERY,
    UTILITIES,
    INSURANCE,
    ENTERTAINMENT,
    HOUSING,
    DEBT_PAYMENTS,
    HEALTH_CARE,
    MEMBERSHIPS_AND_SUBSCRIPTIONS,
    HOME_MAINTENANCE,
    TAXES,
    CLOTHING,
    PERSONAL_CARE,
    TRANSPORTATION,
    EDUCATION,
    FOOD_AND_DINING,
    GIFTS_AND_DONATIONS,
    INVESTMENT,
    TRAVEL,
    OTHERS
}